import { Injectable } from '@angular/core';
import { AppApiService } from '../api/app-api.service';
import { AppStateStoreService } from '../stateManagement/app-state-store.service';
import { Observable } from 'rxjs';
import { tap } from 'rxjs/operators';
import { Person } from 'src/models/Person';

@Injectable({
  providedIn: 'root'
})
export class AppFacadeService {

  constructor(private applicationAPI: AppApiService, private applicationState: AppStateStoreService) { }

  isUpdating$(): Observable<boolean> {
    return this.applicationState.isUpdating$();
  }

  getPersons$(): Observable<Person[]> {
    // here we just pass the state without any projections
    // it may happen that it is necessary to combine two or more streams and expose to the components
    return this.applicationState.getPersons$();
  }

  loadPersons() {
    return this.applicationAPI.getPersons()
      .pipe(tap(persons => this.applicationState.setPersons(persons)));
  }

  // optimistic update
  // 1. update UI state
  // 2. call API
  addPerson(person: Person) {
    this.applicationState.addPerson(person);
    this.applicationAPI.createPerson(person)
      .subscribe(
        (addedPersonWithId: Person) => {
          // success callback - we have id generated by the server, let's update the state
          this.applicationState.updatePersonId(person, addedPersonWithId)
        },
        (error: any) => {
          // error callback - we need to rollback the state change
          this.applicationState.removePerson(person);
          console.log(error);
        }
      );
  }

  // pessimistic update
  // 1. call API
  // 2. update UI state
  updatePerson(person: Person) {
    this.applicationState.setUpdating(true);
    this.applicationAPI.updatePerson(person)
      .subscribe(
        () => this.applicationState.updatePerson(person),
        (error) => console.log(error),
        () => this.applicationState.setUpdating(false)
      );
  }
}
